language: objective-c
env:
 global:
   - MODULE_NAME=ti.coremotion
   - MODULE_VERSION=1.1.0
before_install:
    - MODULE_ROOT="${PWD}"
install:
    - curl -o install.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/install.sh
    - source install.sh -s "--branch 3_5_X"
script: 
    - ./build.sh
    - mkdir -p "$MODULE_ROOT/s3"
    - NOW=$(date +"%Y%m%d%H%M")
    - echo "cp -p \"${MODULE_ROOT}/build/${MODULE_NAME}-iphone-${MODULE_VERSION}.zip\" \"${MODULE_ROOT}/s3/${MODULE_NAME}-iphone-${MODULE_VERSION}-${TRAVIS_BRANCH}-${NOW}.zip\""
    - cp -p "${MODULE_ROOT}/build/${MODULE_NAME}-iphone-${MODULE_VERSION}.zip" "${MODULE_ROOT}/s3/${MODULE_NAME}-iphone-${MODULE_VERSION}-${TRAVIS_BRANCH}-${NOW}.zip"
